### ISSUE TITLE
Exception when opening app

### ISSUE THREAD

**Issue by Camandros** [ODiogoSilva/TriFusion#162]
The app runs normally, but sends the following exception:

Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
     self.run()
   File "/usr/lib/python2.7/threading.py", line 763, in run
     self.__target(*self.__args, **self.__kwargs)
   File "/usr/lib/python2.7/dist-packages/kivy/input/providers/mtdev.py", line 219, in _thread_run
     _device = Device(_fn)
   File "/usr/lib/python2.7/dist-packages/kivy/lib/mtdev.py", line 141, in __init__
     self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)
 OSError: [Errno 13] Permission denied: '/dev/input/event3'

This exception started appearing after Kivy was updated, it's most likely connected.

**Comment by ODiogoSilva** [comment]
This has to do with kivy's automatic detection of multi-touch and I don't expect it to impact the app. However, this error pop's up in my machine since kivy 1.9.0.

https://groups.google.com/forum/#!topic/kivy-users/SJPRF0KQrqg
