### ISSUE TITLE
deleting files in use by the app, using system file manager 

### ISSUE THREAD

**Issue by tiagofilipe12** [ODiogoSilva/TriFusion#193]
causes the app to crash.

 Traceback (most recent call last):
   File ".\TriFusion.py", line 8586, in <module>
     TriFusionApp().run()
   File "C:\Users\Tiago\Anaconda2\lib\site-packages\kivy\app.py", line 828, in run
     runTouchApp()
   File "C:\Users\Tiago\Anaconda2\lib\site-packages\kivy\base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\Tiago\Anaconda2\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
     self._mainloop()
   File "C:\Users\Tiago\Anaconda2\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
     EventLoop.idle()
   File "C:\Users\Tiago\Anaconda2\lib\site-packages\kivy\base.py", line 330, in idle
     self.dispatch_input()
   File "C:\Users\Tiago\Anaconda2\lib\site-packages\kivy\base.py", line 315, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\Tiago\Anaconda2\lib\site-packages\kivy\base.py", line 281, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
   File "C:\Users\Tiago\Anaconda2\lib\site-packages\kivy\uix\behaviors\button.py", line 138, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7654)
   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
   File "kivy\_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy\_event.c:13023)
   File ".\TriFusion.py", line 1876, in <lambda>
     on_release=lambda val: func(bt_wgt))
   File ".\TriFusion.py", line 4033, in remove_bt
     self.alignment_list.remove_file([file_path])
   File "C:\Users\Tiago\Desktop\TriFusion-master\process\sequence.py", line 2059, in remove_file
     self.alignments[nm].remove_alignment()
 KeyError: 'concat.fas'

**Comment by ODiogoSilva** [comment]
Removal of certain directories will also cause nasty problems.

**Comment by tiagofilipe12** [comment]
Can't replicate this issue. The app seems to normally load the files and store them elsewhere. Thus, removing the original input files doesn't crash the app, per se.
